'use client';

import React, { useState } from 'react';
import { Settings, ShieldAlert, HelpCircle } from 'lucide-react';

export default function SettingsPage() {
  const [message, setMessage] = useState('');
  const pauseAll = async () => {
    if (!confirm('Pause every active automation? No messages will be sent until you reactivate them.')) return;
    const response = await fetch('/api/automations/pause-all', { method: 'POST' });
    const data = await response.json();
    setMessage(response.ok ? `${data.paused} automation(s) paused.` : data.error || 'Unable to pause automations.');
  };
  return <div className="space-y-8 max-w-7xl mx-auto"><div><h1 className="text-2xl font-bold text-white flex items-center gap-2"><Settings className="w-6 h-6 text-fuchsia-500" /> Platform Settings & Meta Developer Guide</h1><p className="text-slate-400 text-sm">System environment configuration and Meta App setup guide.</p></div><div className="bg-slate-950 p-6 rounded-2xl border border-slate-800 space-y-4"><h2 className="text-lg font-bold text-white flex items-center gap-2"><HelpCircle className="w-5 h-5 text-fuchsia-400" /> Meta Developer App Setup Guide</h2><div className="space-y-3 text-xs text-slate-300"><div className="bg-slate-900 p-4 rounded-xl border border-slate-800 space-y-2"><h3 className="font-bold text-white text-sm">Webhook Callback</h3><div className="font-mono bg-slate-950 p-3 rounded border border-slate-800 space-y-1 text-slate-200"><div>Callback URL: <span className="text-emerald-400">https://insta-automation-vert.vercel.app/api/webhooks/meta</span></div><div>Verify Token: <span className="text-fuchsia-300">Set private META_VERIFY_TOKEN in Vercel</span></div><div>Subscribed Field: <span className="text-amber-300">comments</span> under the <span className="text-slate-100">instagram</span> object</div></div></div><div className="bg-slate-900 p-4 rounded-xl border border-slate-800 space-y-2"><h3 className="font-bold text-white text-sm">Required Meta Permissions</h3><div className="flex flex-wrap gap-2 pt-1 font-mono text-[11px]">{['instagram_basic', 'instagram_manage_comments', 'instagram_manage_messages', 'pages_read_engagement', 'pages_show_list', 'pages_manage_metadata'].map((permission) => <span key={permission} className="px-2 py-1 rounded bg-slate-950 border border-slate-800 text-fuchsia-300">{permission}</span>)}</div></div></div></div><div className="bg-rose-950/20 p-6 rounded-2xl border border-rose-900/50 space-y-4"><h2 className="text-lg font-bold text-rose-300 flex items-center gap-2"><ShieldAlert className="w-5 h-5 text-rose-400" /> Emergency Kill Switch</h2><p className="text-xs text-rose-200">Immediately pauses all active automations.</p><div className="flex flex-wrap gap-3 pt-2"><button onClick={pauseAll} className="px-4 py-2 rounded-xl bg-rose-600 hover:bg-rose-500 text-white font-medium text-xs shadow-lg shadow-rose-600/30">Pause All Automations</button>{message && <p className="text-xs text-rose-200 self-center">{message}</p>}</div></div></div>;
}
